#! /bin/sh
### BEGIN INIT INFO
# Provides:             auto-idle
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Spindown Harddrives
### END INIT INFO

case "$1" in
  start)
	echo -n "Starting auto-idle: "
	start-stop-daemon --start --quiet --exec auto-idle
	echo "done"
	;;
  stop)
	echo -n "Stopping auto-idle: "
	start-stop-daemon --stop --quiet --exec  auto-idle
	echo "done"
	;;
  restart)
  	$0 stop
	$0 start
	;;
  *)
	echo "Usage: syslog { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
